name: Update package - manual version

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: "Choose version type"
        type: choice
        required: true
        default: "patch"
        options:
          - patch
          - minor
          - major
          - beta
          - downgrade

permissions:
  contents: write
  packages: write

jobs:
  update_pkg_stable_version:
    name: Update package - Manual
    uses: ./.github/workflows/update_pkg.yml
    with:
      version-command: |
        if [[ "${{ github.event.inputs.version-type }}" == "patch" ]]; then
          npm version patch --no-git-tag-version
        elif [[ "${[ github.event.inputs.version-type }}" == "minor" ]]; then
          npm version minor --no-git-tag-version
        elif [[ "${{ github.event.inputs.version-type }}" == "major" ]]; then
          npm version major --no-git-tag-version
        elif [[ "${{ github.event.inputs.version-type }}" == "beta" ]]; then
          if [ "${{ needs.update_pkg_stable_version.outputs.is_beta }}" == "true" ]; then
            npm version prerelease --preid=beta --no-git-tag-version
          else
            npm version prepatch --preid=beta --no-git-tag-version
          fi
        elif [[ "${{ github.event.inputs.version-type }}" == "downgrade" ]]; then
          npm version ${{ needs.update_pkg_stable_version.outputs.previous_version }}
        fi