name: Update package - manual version

on:
  workflow_dispatch:
    branches-ignore:
      - main
    inputs:
      publish-pkg:
        description: Publish Package
        type: boolean
        default: false
        required: true
      version-type:
        description: "Choose version type"
        type: choice
        required: true
        default: "patch"
        options:
          - patch
          - minor
          - major
          - beta
          - downgrade

permissions:
  contents: write
  packages: write

jobs:
  update_pkg_version:
    name: Update package - Manual
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: ${{ github.event.inputs.version-type }}
  publish_pkg:
    if: ${{ github.event.inputs.publish-pkg }}
    name: Publish package
    needs: update_pkg_version
    uses: ./.github/workflows/publish_pkg.yml