name: Update package - manual version

on:
  workflow_dispatch:
    branches:
      - '**'
    inputs:
      publish-pkg:
        description: Publish Package
        type: boolean
        default: false
        required: true
      version-type:
        description: "Choose version type"
        type: choice
        required: true
        default: "beta"
        options:
          - patch
          - minor
          - major
          - beta
          - downgrade

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  request_approval:
    runs-on: ubuntu-latest
    steps:
      - name: Request approval
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: manual-approval

  update_pkg_version:
    name: Update package - Manual
    needs: request_approval
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: ${{ github.event.inputs.version-type }}

  publish_pkg:
    name: Publish package
    needs: update_pkg_version
    if: ${{ github.event.inputs.publish-pkg == 'true' }}
    uses: ./.github/workflows/publish_pkg.yml
    secrets: inherit