name: Update package - downgrade version

on:
  pull_request:
    types: [closed]
    branches:
      - release/**
      - feature/**
      - fix/**
      - main

permissions:
  contents: write
  packages: write

jobs:
  downgrade_pkg_version:
    if: ${{ github.event.pull_request.merged == false }}
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: 'downgrade'