name: Update package - manual version

on:
  workflow_dispatch:
    branches:
      - '**'
    inputs:
      publish-pkg:
        description: Publish Package
        type: boolean
        default: false
        required: true
      version-type:
        description: "Choose version type"
        type: choice
        required: true
        default: "beta"
        options:
          - patch
          - minor
          - major
          - beta
          - downgrade

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure Git credentials
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Create a new branch
        run: |
          git checkout -b temp/approval-branch

      - name: Commit changes
        run: |
          git commit --allow-empty -m "Requesting approval"

      - name: Push the branch
        run: |
          git push origin temp/approval-branch

      - name: create pull request
        run: |
          gh pr create \ 
            -B temp/approval-branch \
            -H ${{ github.ref }} \
            --title 'Merge branch_to_merge into base_branch' \
            --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  wait_for_approval:
    needs: create_pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Wait for PR approval and merge
        uses: peter-evans/wait-for-check@v2
        with:
          ref: ${{ github.ref }}
          check-name: Approval Required
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          interval-seconds: 60
          timeout-seconds: 3600

  update_pkg_version:
    name: Update package - Manual
    needs: wait_for_approval
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: ${{ github.event.inputs.version-type }}

  publish_pkg:
    name: Publish package
    needs: update_pkg_version
    if: ${{ github.event.inputs.publish-pkg == 'true' }}
    uses: ./.github/workflows/publish_pkg.yml
    secrets: inherit