name: Update package - manual version

on:
  workflow_dispatch:
    branches-ignore:
      - main
    inputs:
      publish-pkg:
        description: Publish Package
        type: boolean
        default: false
        required: true
      version-type:
        description: "Choose version type"
        type: choice
        required: true
        default: "beta"
        options:
          - patch
          - minor
          - major
          - beta
          - downgrade

permissions:
  id-token: write
  contents: read

jobs:
  approval-gate:
    environment: manual-deploy
    runs-on: ubuntu-latest
    steps:
      - name: approved
        run: echo "Approve for manual-deploy"

  update_pkg_version:
    name: Update package - Manual
    needs: approval-gate
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: ${{ github.event.inputs.version-type }}

  publish_pkg:
    name: Publish package
    needs: update_pkg_version
    if: ${{ github.event.inputs.publish-pkg == 'true' }}
    uses: ./.github/workflows/publish_pkg.yml
    secrets: inherit