name: Update package - stable version

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  update_pkg_stable_version:
    name: Update package - Stable Version
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: |
        if [[ "${{ github.head_ref }}" == "fix/"* ]]; then
          'patch'
        elif [[ '${{ github.head_ref }}" == "feature/"* ]]; then
          'minor'
        elif [[ "${{ github.head_ref }}" == "release/"* || "${{ github.head_ref }}" == "major/"* ]]; then
          'major'
        else
          echo "Branch not recognized for automatic versioning."
          exit 1
        fi