name: Update package - beta version

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - release/**
      - feature/**
      - fix/**

permissions:
  contents: write
  packages: write

jobs:
  update_pkg_beta_version:
    name: Update package - Stable Version
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: 'beta'
