name: Update package - manual version

on:
  workflow_dispatch:
    branches-ignore:
      - main
    inputs:
      version-type:
        description: "Choose version type"
        type: choice
        required: true
        default: "patch"
        options:
          - patch
          - minor
          - major
          - beta
          - downgrade

permissions:
  contents: write
  packages: write

jobs:
  update_pkg_stable_version:
    name: Update package - Manual
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: ${{ github.event.inputs.version-type }}