name: Update package - manual version

on:
  pull_request:
    types: [closed]
    branches:
      - '**'

permissions:
  contents: read

jobs:
  downgrade_pkg_version:
    if: ${{ github.event.pull_request.merged == false }}
    uses: ./update_pkg.yml
    with:
      job-name: Downgrade Version
      version-command: npm version ${{ needs.downgrade_pkg_version.outputs.previousVersion }}