name: Update package - stable version

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

permissions:
  contents: write
  packages: write

jobs:
  determine_version_type:
    name: Determine version type
    runs-on: ubuntu-latest

    outputs:
      version_type: ${{ steps.determine_version.outputs.version_type }}
    
    steps:
      - name: Identifying the type
        id: determine_version
        run: |
          if [[ "${{ github.head_ref }}" == "refs/heads/fix/"* ]]; then
            echo "version_type=patch" >> $GITHUB_OUTPUT
          elif [[ "${{ github.head_ref }}" == "refs/heads/feature/"* ]]; then
            echo "version_type=minor" >> $GITHUB_OUTPUT
          elif [[ "${{ github.head_ref }}" == "refs/heads/release/"* || "${{ github.ref }}" == "refs/heads/major/"* ]]; then
            echo "version_type=major" >> $GITHUB_OUTPUT
          else
            echo "Branch not recognized for automatic versioning."
            exit 1
          fi

  update_pkg_stable_version:
    name: Update package - Stable Version
    needs: determine_version_type
    uses: ./.github/workflows/update_pkg.yml
    with:
      command-type: ${{ needs.determine_version_type.outputs.version_type }}