name: Update package - manual version

on:
  workflow_dispatch:
    inputs:
      version-type:
        description: "Choose version type"
        required: true
        default: "patch"
        options:
          - patch
          - minor
          - major
          - beta


permissions:
  contents: read

jobs:
  update_pkg_stable_version:
    name: Update package - Manual
    uses: ./.github/workflows/update_pkg.yml
    with:
      version-command: |
        if [[ "${{ github.event.inputs.version-type }}" == "patch" ]]; then
          npm version patch --no-git-tag-version
        elif [[ "${[ github.event.inputs.version-type }}" == "minor" ]]; then
          npm version minor --no-git-tag-version
        elif [[ "${{ github.event.inputs.version-type }}" == "major" ]]; then
          npm version major --no-git-tag-version
        else
          echo "Invalid version choice: ${{ github.event.inputs.version-type }}"
          exit 1
        fi
      github-token: ${{ secrets.GITHUB_TOKEN }}